AssortmentSolution/WebApp/Controllers/ChainsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Contracts.DAL.App;
using Microsoft.AspNetCore.Mvc;
using Domain;
using Microsoft.AspNetCore.Authorization;

namespace WebApp.Controllers
{
    [Authorize]
    public class ChainsController : Controller
    {
        private readonly IAppUnitOfWork _uow;
        
        public ChainsController(IAppUnitOfWork uow)
        {
            _uow = uow;
        }

        // GET: Chains
        public async Task<IActionResult> Index(string? search)
        {
            //List<Chain> chains = new List<Chain>();  
            if (string.IsNullOrWhiteSpace(search))
            {
                return View(new List<Chain>());
            }
            return View(await _uow.Chains.FindChainsAsync(search));
        }

        // GET: Chains/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chain = await _uow.Chains.FindAsync(id);
            if (chain == null)
            {
                return NotFound();
            }

            return View(chain);
        }

        // GET: Chains/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Chains/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ChainName,Id,CreatedBy,CreatedAt,DeletedBy,DeletedAt")] Chain chain)
        {
            if (!ModelState.IsValid) return View(chain);
            chain.CreatedAt = DateTime.Now;
            chain.CreatedBy = User.Identity.Name;
            _uow.Chains.Add(chain);
            await _uow.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Chains/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chain = await _uow.Chains.FindAsync(id);
            if (chain == null)
            {
                return NotFound();
            }
            return View(chain);
        }

        // POST: Chains/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("ChainName,Id,CreatedBy,CreatedAt,DeletedBy,DeletedAt")] Chain chain)
        {
            if (id != chain.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid) return View(chain);
            _uow.Chains.Update(chain);
            await _uow.SaveChangesAsync();
                
            return RedirectToAction(nameof(Index));
        }

        // GET: Chains/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chain = await _uow.Chains.FindAsync(id);
            if (chain == null)
            {
                return NotFound();
            }

            return View(chain);
        }

        // POST: Chains/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            _uow.Chains.Remove(id);
            await _uow.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

AssortmentSolution/WebApp/Controllers/OrdersController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Threading.Tasks;
using Contracts.DAL.App;
using Domain;
using Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IAppUnitOfWork _uow;
        
        public OrdersController(IAppUnitOfWork uow)
        {
            _uow = uow;
        }
        
        [HttpPost]
        public Task<IActionResult> Assortment(Guid id, ProductInShopsCheckboxViewModel vm)
        {
            if (vm.Checkboxes!.Count == 0)
            {
                return Task.FromResult<IActionResult>(RedirectToAction(nameof(Index)));
            }
            
            string subject = "Puuduolevad kaubad: " + vm.Shop.ShopName;
            const string beginning = "Tere! \n\nJärgmised kaubad olid puudu: \n";
            Person person = _uow.Persons.FindAsync(vm.Shop.PersonId).Result;
            string end = "\n\nTervitades, \n" + person.FirstName + " " + person.LastName + "\n" + person.PhoneNumber;
            Console.WriteLine(end);
            string body;
            
            var fromAddress = new MailAddress(User.Identity.Name);
            var toAddress = new MailAddress(User.Identity.Name, "To Name");
            MailMessage message = new MailMessage(fromAddress, toAddress);
            message.Subject = subject;

            List<Product> products = new List<Product>();
            
            foreach (var cb in vm.Checkboxes)
            {
                if (!cb.IsSelected)
                {
                    Product product = 
                        new Product {Barcode = cb.Barcode, ProductName = cb.ProductName};
                    products.Add(product);
                }
            }
            
            if (products.Count == 0)
            {
                body = "Kõik tooted on olemas!";
            }
            else
            {
                StringBuilder sb = new StringBuilder();
                sb.Append(beginning);
                foreach (var item in products)
                {
                    sb.Append(item.Barcode).Append("\t").Append(item.ProductName).Append("\n");
                }
                
                sb.Append(end);
                body = sb.ToString();
                if (vm.Shop.ShopEmail != User.Identity.Name)
                {
                    message.CC.Add(vm.Shop.ShopEmail);
                }
            }

            message.Body = body;
            
            var smtp = new SmtpClient
            {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                UseDefaultCredentials = false,
                Credentials = new NetworkCredential("balmerkmail@gmail.com", "Raudtee9")
            };
            
            smtp.Send(message);
            return Task.FromResult<IActionResult>(RedirectToAction(nameof(Index)));
        }
        
        public async Task<IActionResult> Index(string? search)
        {
            if (string.IsNullOrWhiteSpace(search))
            {
                return View();
            }
            if (search.Equals("*"))
            {
                return View(await _uow.Shops.AllAsync());
            }
            return View(await _uow.Shops.FindShopsAsync(search));
        }

        public Task<IActionResult> Assortment(Guid id)
        {
            if (id == null)
            {
                return Task.FromResult<IActionResult>(NotFound());
            }
            
            IEnumerable<ProductInShop> products = _uow.ProductInShops.GetAllProducts(id);

            ProductInShopsCheckboxViewModel vm = new ProductInShopsCheckboxViewModel
            {
                Shop = _uow.ProductInShops.GetShop(id)
            };

            foreach (var p in products)
            {
                vm.Checkboxes!.Add(new CheckboxViewModel
                {
                    ProductName = p.Product!.ProductName,
                    Barcode = p.Product.Barcode,
                    ProductId = p.ProductId
                });
            }
            
            return Task.FromResult<IActionResult>(View(vm));
        }
    }
}

AssortmentSolution/WebApp/Controllers/ShopsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Contracts.DAL.App;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL.App.EF;
using Domain;
using Microsoft.AspNetCore.Authorization;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    [Authorize]
    public class ShopsController : Controller
    {
        private readonly IAppUnitOfWork _uow;

        public ShopsController(IAppUnitOfWork uow)
        {
            _uow = uow;
        }

        // GET: Shops
        public async Task<IActionResult> Index()
        {
            return View(await _uow.Shops.AllAsync());
        }

        // GET: Shops/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shop = await _uow.Shops.FindAsync(id);
            if (shop == null)
            {
                return NotFound();
            }

            return View(shop);
        }

        // GET: Shops/Create
        public IActionResult Create()
        {
            var vm = new ShopCreateEditViewModel();
            vm.ChainSelectList = new SelectList(_uow.Chains.All(), nameof(Chain.Id), nameof(Chain.ChainName));
            vm.CooperativeSelectList = new SelectList(_uow.Cooperatives.All(), nameof(Cooperative.Id), nameof(Cooperative.CooperativeName));
            vm.PersonSelectList = new SelectList(_uow.Persons.All(), nameof(Person.Id), nameof(Person.FirstName));
            return View(vm);
        }

        // POST: Shops/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ShopCreateEditViewModel vm)
        {
            Console.WriteLine(vm.Shop!.ShopName);
            if (ModelState.IsValid)
            {
                _uow.Shops.Add(vm.Shop!);
                await _uow.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            
            vm.ChainSelectList = new SelectList(await _uow.Chains.AllAsync(), nameof(Chain.Id), nameof(Chain.ChainName), vm.Shop!.ChainId);
            vm.CooperativeSelectList = new SelectList(await _uow.Cooperatives.AllAsync(), nameof(Cooperative.Id), nameof(Cooperative.CooperativeName), vm.Shop.CooperativeId);
            vm.PersonSelectList = new SelectList(await _uow.Persons.AllAsync(), nameof(Person.Id), nameof(Person.FirstName), vm.Shop.PersonId);
            return View(vm);
        }

        // GET: Shops/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shop = await _uow.Shops.FindAsync(id);
            if (shop == null)
            {
                return NotFound();
            }
            ShopCreateEditViewModel vm = new ShopCreateEditViewModel();
            vm.Shop = shop;
            vm.ChainSelectList = new SelectList(await _uow.Chains.AllAsync(), nameof(Chain.Id), nameof(Chain.ChainName));
            vm.CooperativeSelectList = new SelectList(await _uow.Cooperatives.AllAsync(), nameof(Cooperative.Id), nameof(Cooperative.CooperativeName));
            vm.PersonSelectList = new SelectList(await _uow.Persons.AllAsync(), nameof(Person.Id), nameof(Person.FirstName));
            return View(vm);
        }

        // POST: Shops/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, ShopCreateEditViewModel vm)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                vm.Shop!.Id = (Guid) id!;
                 _uow.Shops.Update(vm.Shop);
                 await _uow.SaveChangesAsync();
                 return RedirectToAction(nameof(Index));
            }
            vm.ChainSelectList = new SelectList(await _uow.Chains.AllAsync(), nameof(Chain.Id), nameof(Chain.ChainName), vm.Shop!.ChainId);
            vm.CooperativeSelectList = new SelectList(await _uow.Cooperatives.AllAsync(), nameof(Cooperative.Id), nameof(Cooperative.CooperativeName), vm.Shop.CooperativeId);
            vm.PersonSelectList = new SelectList(await _uow.Persons.AllAsync(), nameof(Person.Id), nameof(Person.FirstName), vm.Shop.PersonId);
            
            return View(vm);
        }

        // GET: Shops/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shop = await _uow.Shops.FindAsync(id);
            if (shop == null)
            {
                return NotFound();
            }

            return View(shop);
        }

        // POST: Shops/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            _uow.Shops.Remove(id);
            await _uow.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

AssortmentSolution/WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
    @RenderSection("Styles", false)
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartial"/>
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Chains" asp-action="Index">Chains</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Cooperatives" asp-action="Index">Cooperatives</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Divisions" asp-action="Index">Divisions</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Sortimendi kontroll</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Persons" asp-action="Index">Persons</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Shops" asp-action="Index">Shops</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="ProductInShops" asp-action="Index">ProductInShops</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>

AssortmentSolution/WebApp/Views/Shared/_Search.cshtml
<link rel="stylesheet" href="css/site.css">
<div class="container">
    <br/>
    <div class="row justify-content-center">
        <div class="col-12 col-md-10 col-lg-8">
            <form class="card card-sm" method="get">
                <div class="card-body row no-gutters align-items-center">
                    <!--end of col-->
                    <div class="col">
                        <input class="form-control form-control-lg form-control-borderless" name="search" type="search" placeholder="Otsi klienti">
                    </div>
                    <!--end of col-->
                    <div class="col-auto">
                        <button asp-action="" asp-route-queryString="search" class="btn btn-lg btn-success" type="submit">Search</button>
                    </div>
                    <!--end of col-->
                </div>
            </form>
        </div>
        <!--end of col-->
    </div>
</div>